# Generated by Django 3.1.3 on 2020-11-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at', 'title', 'pk']},
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(unique=True),
        ),
    ]
